name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.4.8'
        #cabal-version: '2.4'

    - name: Cache Cabal packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal', '**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-cabal-

    - name: Update Cabal package list
      run: cabal update

    - name: build
      run: make

    # - name: Build Clash project
    #   run: cabal build

    # - name: Run tests (if any)
    #   run: cabal test
